### PR TITLE
feat: Initial version

### PR DESCRIPTION
**Pull request by oscard0m**
Your new script is ready to be implemented :tada:

You can run it locally on your machine with

```
node cli.js
```

Once you are happy with it, push your changes to this pull request

```
git commit -a -m "feat: initial version"
git push
```

Before merging:

- [x] [Install the Octoherd GitHub App](https://github.com/apps/octoherd/installations/new/permissions?suggested_target_id=2574275&repository_ids[]=372769957)
- [x] Add `NPM_TOKEN` to the [repository secrets](https://github.com/oscard0m/octoherd-script-sync-repo-settings/settings/secrets). Set it to an [npm automation token](https://docs.npmjs.com/creating-and-viewing-access-tokens#creating-access-tokens)

-----
[View rendered README.md](https://github.com/oscard0m/octoherd-script-sync-repo-settings/blob/initial-version/README.md)

### CODE REVIEW

**Comment by gr2m** [comment]
probably not a bug with your script but with Octoherd, but I was surprised to see the `msg` option in the `PATCH /repos/{owner}/{repo}` request

image

**Update:** also where does the `name` parameter come from?

**Comment by gr2m** [comment]
no need to do this as part of the initial version, but maybe create issues for later:

- [ ] do not update template repository (EDIT: https://github.com/oscard0m/octoherd-script-sync-repo-settings/issues/2)
- [ ] do not update repository which already has the settings from the template repository (EDIT: https://github.com/oscard0m/octoherd-script-sync-repo-settings/issues/3)

**Comment by oscard0m** [comment]
> **Update:** also where does the `name` parameter come from?

https://docs.github.com/en/rest/reference/repos#update-a-repository seems that the docs are duplicating the parameter (`repo` and `name`)? @gr2m

**Comment by oscard0m** [comment]
> probably not a bug with your script but with Octoherd, but I was surprised to see the `msg` option in the `PATCH /repos/{owner}/{repo}` request
> 
> image

Follow up as a discussion here before opening an issue: https://github.com/octoherd/octoherd/discussions/23

**Comment by gr2m** [comment]
> https://docs.github.com/en/rest/reference/repos#update-a-repository seems that the docs are duplicating the parameter (`repo` and `name`)? @gr2m

You can use `name` to change the name of the repository. `repo` is the current name

**Comment by oscard0m** [comment]
> > https://docs.github.com/en/rest/reference/repos#update-a-repository seems that the docs are duplicating the parameter (`repo` and `name`)? @gr2m
> 
> You can use `name` to change the name of the repository. `repo` is the current name

Ohhh I see, I didn't know that `name` parameter was used for renaming. I'm going to remove it from this script then. Thanks! 👍🏽

**Pull request merged**
